import { afterEach, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, waitFor } from '@testing-library/svelte';
import { writable } from 'svelte/store';
vi.mock('$app/navigation', () => ({ goto: vi.fn(), replaceState: vi.fn(), beforeNavigate: vi.fn(), afterNavigate: vi.fn() }));
vi.mock('svelte/transition', () => ({ fade: () => ({}), fly: () => ({}), scale: () => ({}) }));
vi.mock('$lib/components/layout/DashboardLayout.svelte', async () => ({ default: (await import('../pipeline/TestLayout.svelte')).default }));
vi.mock('$lib/convex.js', () => ({ isDemoMode: () => false, getConvexHttpClient: () => null, getConvexClient: async () => null }));
vi.mock('$lib/auth/session.js', () => ({ session: writable({ status: 'authenticated', user: { id: 'reporter', role: 'owner', canViewConfidential: true } }) }));
vi.mock('$lib/stores/filterStore.js', () => ({ dateRange: writable({ label: 'July–September', startDate: '2026-07-01', endDate: '2026-09-30' }) }));
vi.mock('$lib/services/peopleService.js', () => ({ getAll: async () => ({ data: [], error: null }), formatJourneyStatus: () => 'Member' }));
vi.mock('$lib/services/evangelismService.js', () => ({ getAll: async () => ({ data: [{ id: 'old', first_name: 'Early', contact_date: '2026-07-04' }, { id: 'joined', first_name: 'Joined', contact_date: '2026-09-09', member_status: 'member' }], error: null }) }));
vi.mock('$lib/services/servicesService.js', () => ({ getAll: async () => ({ data: [], error: null }) }));
vi.mock('$lib/services/meetingsService.js', () => ({ getAll: async () => ({ data: [], error: null }) }));
vi.mock('$lib/services/visitationsService.js', () => ({ getAll: async () => ({ data: [], error: null }) }));
afterEach(() => { cleanup(); vi.useRealTimers(); vi.unstubAllGlobals(); });

it('opens Series B average through zero months to exact source and keeps CSV state on return', async () => {
  vi.setSystemTime(new Date(2026, 8, 24));
  vi.stubGlobal('scrollTo', vi.fn());
  const { default: Page } = await import('./+page.svelte');
  const view = render(Page);
  await waitFor(() => expect(view.getByRole('button', { name: 'Inspect New Contacts' })).toBeInTheDocument());
  await fireEvent.change(view.getByLabelText('Records to download'), { target: { value: 'contacts' } });
  await fireEvent.change(view.getByLabelText('Person'), { target: { value: '' } });
  const typeBefore = view.getByLabelText('Records to download').value;
  await fireEvent.click(view.getByText('Detailed report metrics and comparisons'));
  await fireEvent.change(view.getByLabelText('Primary metric'), { target: { value: 'joinedChurch' } });
  await fireEvent.change(view.getByLabelText('Comparison metric'), { target: { value: 'joinedChurch' } });
  await fireEvent.click(view.getByRole('button', { name: /Series B · Reached people who joined/ }));
  const dialog = view.getByRole('dialog', { name: 'Reached people who joined' });
  expect(dialog).toHaveTextContent('1 ÷ 3 calendar months ≈ 0 (rounded to a whole count)');
  expect(dialog).toHaveTextContent('2026-07: 0');
  expect(dialog).toHaveTextContent('2026-08: 0');
  await fireEvent.click(view.getByRole('button', { name: /2026-09: 1/ }));
  expect(dialog).toHaveTextContent('2026-09 · Reached people who joined');
  await fireEvent.click(view.getByRole('button', { name: 'View contact' }));
  expect(dialog).toHaveTextContent('Joined');
  await fireEvent.click(view.getByRole('button', { name: 'Back to previous details' }));
  expect(dialog).toHaveTextContent('2026-09 · Reached people who joined');
  expect(view.getByLabelText('Records to download').value).toBe(typeBefore);
  const saved = view.component.snapshot.capture();
  expect(JSON.stringify(saved)).not.toContain('Joined');
  view.unmount();
  const returned = render(Page);
  returned.component.snapshot.restore(saved);
  await waitFor(() => expect(returned.getByRole('dialog', { name: '2026-09 · Reached people who joined' })).toHaveTextContent('2026-09 · Reached people who joined'));
  await waitFor(() => expect(returned.getByLabelText('Records to download').value).toBe(typeBefore));
  await new Promise(resolve => requestAnimationFrame(resolve));
}, 15000);
